#!/usr/bin/env bash
# Take the course's screenshots and demonstration video, reproducibly.
#
# Everything the slides show is generated by this script rather than captured
# by hand, for the same reason the measurements are: a hand-cropped screenshot
# taken six months from now will not match the numbers in the deck it sits in,
# and nobody will notice.
#
# Run it inside the course container, on the virtual desktop:
#
#   course desktop
#   bash tools/media/capture.sh gazebo-gui        # swap in the recording GUI
#   bash tools/media/capture.sh closeup X Y Z R AZ EL   # frame the aircraft
#   bash tools/media/capture.sh shot NAME         # one frame
#   bash tools/media/capture.sh rec  NAME SECONDS # video
#   bash tools/media/capture.sh term 'course sim' # a terminal running something
#   bash tools/media/capture.sh frame TOPIC NAME  # one frame off an image topic
#   bash tools/media/capture.sh rviz              # RViz with the course layout
#   bash tools/media/capture.sh qgc               # QGroundControl
#
# Output goes to $MEDIA (default ~/media).
set -uo pipefail

MEDIA="${MEDIA:-$HOME/media}"
# The Gazebo render area inside a 1920x1080 window: everything below the
# toolbars, left of the entity tree, above the playback buttons.
#
# Cropping rather than configuring. `gz sim -g --gui-config` with a
# scene-only layout is the tidier idea and it did not take -- the stock
# panels came back regardless -- and a deterministic crop is worth more here
# than a clean solution that silently does not apply.
GZ_CROP="${GZ_CROP:-1500x860+0+148}"
export DISPLAY="${DISPLAY:-:99}"
CLEAN_GUI="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/gui_clean.config"
mkdir -p "$MEDIA"

need() { command -v "$1" >/dev/null || { echo "missing: $1 (apt-get install $2)"; exit 1; }; }
need ffmpeg ffmpeg
need import imagemagick
need xdotool xdotool

# The pointer is an ugly, meaningless arrow in the middle of every frame.
# ffmpeg can be told not to draw it; `import` cannot, so park it off-screen.
park_pointer() { xdotool mousemove 1919 1079 2>/dev/null; }

fullscreen() {
    local title="$1" id=""
    for _ in $(seq 20); do
        id="$(xdotool search --name "$title" 2>/dev/null | tail -1)"
        [ -n "$id" ] && break
        sleep 1
    done
    [ -z "$id" ] && { echo "no window titled '$title'"; return 1; }
    wmctrl -i -r "$id" -b add,fullscreen 2>/dev/null
    xdotool windowactivate "$id" 2>/dev/null
    sleep 2
}

# Replace the GUI PX4 started with one that is nothing but the 3D view.
gazebo_gui() {
    pkill -f "gz sim -g"
    sleep 2
    __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/10_nvidia.json \
    __GLX_VENDOR_LIBRARY_NAME=nvidia \
        nohup gz sim -g --gui-config "$CLEAN_GUI" > /tmp/gzgui.log 2>&1 &
    sleep 12
    fullscreen "Gazebo Sim"
    park_pointer
    echo "recording GUI up"
}

# Aim the shot. Either a fixed pose, or follow a model.
look_at() {   # look_at X Y Z QX QY QZ QW
    gz service -s /gui/move_to/pose --reqtype gz.msgs.GUICamera \
      --reptype gz.msgs.Boolean --timeout 3000 \
      --req "pose: {position: {x: $1, y: $2, z: $3}, orientation: {x: $4, y: $5, z: $6, w: $7}}" \
      >/dev/null 2>&1
}

# Park the camera a few metres off the aircraft and look at it. For the
# stills that have to SHOW the hardware -- the gimbal under the nose, the
# props, the lens pointing down -- rather than show it flying.
#
# Gazebo's camera looks down its own +x, so aiming it means a quaternion, and
# the arithmetic is fiddly enough by hand that it belongs here once.
closeup() {   # closeup TX TY TZ  RANGE  AZIMUTH_DEG  ELEVATION_DEG
    python3 - "$@" <<'PYEOF'
import math, subprocess, sys
tx, ty, tz, rng, az, el = (float(v) for v in sys.argv[1:7])
a, e = math.radians(az), math.radians(el)
x = tx - rng * math.cos(e) * math.cos(a)
y = ty - rng * math.cos(e) * math.sin(a)
z = tz + rng * math.sin(e)
yaw, pitch = a, e                       # look back along the same ray
cy, sy = math.cos(yaw / 2), math.sin(yaw / 2)
cp, sp = math.cos(pitch / 2), math.sin(pitch / 2)
q = (-sy * sp, cy * sp, sy * cp, cy * cp)
subprocess.run(["gz", "service", "-s", "/gui/move_to/pose",
                "--reqtype", "gz.msgs.GUICamera", "--reptype", "gz.msgs.Boolean",
                "--timeout", "3000",
                "--req", f"pose: {{position: {{x: {x}, y: {y}, z: {z}}}, "
                         f"orientation: {{x: {q[0]}, y: {q[1]}, z: {q[2]}, w: {q[3]}}}}}"],
               capture_output=True)
print(f"camera at {x:.1f} {y:.1f} {z:.1f}, {rng:.0f} m from target")
PYEOF
}

follow() {    # follow MODEL  DX DY DZ
    gz service -s /gui/follow --reqtype gz.msgs.StringMsg --reptype gz.msgs.Boolean \
      --timeout 3000 --req "data: \"$1\"" >/dev/null 2>&1
    gz service -s /gui/follow/offset --reqtype gz.msgs.Vector3d \
      --reptype gz.msgs.Boolean --timeout 3000 \
      --req "x: $2, y: $3, z: $4" >/dev/null 2>&1
}

# shot NAME [full]  -- cropped to the Gazebo render area unless 'full'
shot() {
    park_pointer
    sleep 1
    if [ "${2:-}" = "full" ]; then
        import -window root "$MEDIA/$1.png"
    else
        import -window root /tmp/_shot_full.png
        convert /tmp/_shot_full.png -crop "$GZ_CROP" +repage "$MEDIA/$1.png"
    fi
    echo "$MEDIA/$1.png"
}

rec() {
    local name="$1" secs="${2:-60}"
    park_pointer
    # -draw_mouse 0 so a stray pointer never lands in the middle of a demo.
    # 1280x720 at CRF 24: a three-minute clip lands near 15 MB instead of 50,
    # which is the difference between a repository you can clone on conference
    # wifi and one you cannot. It is still more resolution than a projector.
    local size="${GZ_CROP%%+*}" off="${GZ_CROP#*+}"
    [ "${3:-}" = "full" ] && { size="1920x1080"; off="0+0"; }
    ffmpeg -y -f x11grab -draw_mouse 0 -framerate 25 \
        -video_size "$size" -i "${DISPLAY}.0+${off/+/,}" -t "$secs" \
        -vf scale=1280:-2 \
        -c:v libx264 -preset medium -crf 24 -pix_fmt yuv420p -movflags +faststart \
        "$MEDIA/$name.mp4" > "/tmp/ffmpeg_$name.log" 2>&1
    echo "$MEDIA/$name.mp4 ($(du -h "$MEDIA/$name.mp4" | cut -f1))"
}

# A terminal, for the clips that are really about what the console says.
# Big font, dark background, no scrollbar: a 1920x1080 recording downscaled to
# a projector has to stay readable from the back of a room.
term() {      # term "command to run"  [cols] [rows]
    xterm -geometry "${2:-150}x${3:-42}+0+0" \
          -fa 'DejaVu Sans Mono' -fs 15 \
          -bg '#101418' -fg '#e8e8e8' -sb- \
          -title 'course' -e bash -lc "$1" &
    sleep 3
    fullscreen "course"
    park_pointer
}

# Same, but returns immediately so the caller can drive the screen while it
# records -- typing into a console, flying a mission, injecting a blackout.
rec_bg() {
    local name="$1" secs="${2:-60}"
    park_pointer
    local size="1920x1080" off="0+0"
    if [ "${3:-}" != "full" ]; then size="${GZ_CROP%%+*}"; off="${GZ_CROP#*+}"; fi
    ffmpeg -y -f x11grab -draw_mouse 0 -framerate 25 \
        -video_size "$size" -i "${DISPLAY}.0+${off/+/,}" -t "$secs" \
        -vf scale=1280:-2 \
        -c:v libx264 -preset medium -crf 24 -pix_fmt yuv420p -movflags +faststart \
        "$MEDIA/$name.mp4" > "/tmp/ffmpeg_$name.log" 2>&1 &
    echo $!
}

# Type into the terminal `term` opened, as a person would.
type_in() {   # type_in "text to type"  [delay_ms]
    local id
    id="$(xdotool search --name '^course$' | tail -1)"
    [ -z "$id" ] && { echo "no course terminal"; return 1; }
    xdotool type --window "$id" --delay "${2:-60}" -- "$1"
    xdotool key --window "$id" Return
}

rviz_shot() {
    course rviz > /tmp/rviz.log 2>&1 &
    sleep 15
    fullscreen "RViz"
    shot "${1:-rviz}"
}

qgc_shot() {
    course qgc > /tmp/qgc.log 2>&1
    sleep 25
    fullscreen "QGroundControl"
    shot "${1:-qgc}"
}

case "${1:-help}" in
    gazebo-gui) gazebo_gui ;;
    shot)   shift; shot "$@" ;;
    rec)    shift; rec "$@" ;;
    rec-bg) shift; rec_bg "$@" ;;
    type)   shift; type_in "$@" ;;
    rviz)   shift; rviz_shot "$@" ;;
    qgc)    shift; qgc_shot "$@" ;;
    look)   shift; look_at "$@" ;;
    closeup) shift; closeup "$@" ;;
    term)   shift; term "$@" ;;
    frame)  shift; python3 "$(dirname "${BASH_SOURCE[0]}")/grab_topic.py" \
                "${1:-/detector/image_annotated}" "$MEDIA/${2:-detector}.png" "${3:-20}" ;;
    follow) shift; follow "$@" ;;
    *) sed -n '2,20p' "${BASH_SOURCE[0]}" ;;
esac
