#!/usr/bin/env python3
"""Generate the course ground: a seamless grass texture and a tiled mesh.

Why this exists at all. The stock PX4 ground_plane is a single untextured grey
quad, and a grey quad under a grey sky gives a student *no* visual motion cue:
the aircraft can be translating at 4 m/s and the render looks static. That
costs real debugging time in the follow labs, where "is it moving?" is the
first question. It also makes every screenshot in the slides a grey void.

Two decisions worth recording:

  * The ground is a MESH, not a <plane>. A plane visual stretches its texture
    across the whole 500 m, which at any sane texture size is 0.25 m per pixel
    -- blurry mush from 12 m up. The mesh carries UVs that repeat the texture
    once per TILE_M metres, so resolution is set by the tile, not the field.
  * The texture is made seamless by filtering the noise in the frequency
    domain (a wrapped Gaussian), so the tile edges do not show as a grid from
    the air. A plain gaussian_filter leaves visible seams at exactly the
    altitude the course flies at.

The mowing stripes are not decoration. They are a known-pitch ground pattern:
STRIPE_M metres per stripe, so a student can eyeball ground speed from a video
frame, and the detector has structured background rather than a flat field.

Regenerate with:  python3 make_ground.py
"""
import numpy as np
from PIL import Image

PX = 2048          # texture resolution
TILE_M = 20.0      # metres of ground per texture tile -> ~10 mm per pixel
STRIPE_M = 2.5     # mowing stripe pitch; divides TILE_M, so tiles stay seamless
FIELD_M = 3000.0   # ground extent: far enough that the edge of the
                   # mesh is never in shot, which a 500 m field was not
SEED = 7


def seamless_noise(shape, sigma, rng):
    """Gaussian-filtered white noise that wraps at the edges."""
    n = rng.standard_normal(shape)
    fy = np.fft.fftfreq(shape[0])[:, None]
    fx = np.fft.fftfreq(shape[1])[None, :]
    kernel = np.exp(-2.0 * (np.pi * sigma) ** 2 * (fx ** 2 + fy ** 2))
    out = np.real(np.fft.ifft2(np.fft.fft2(n) * kernel))
    return (out - out.mean()) / (out.std() + 1e-9)


def main():
    rng = np.random.default_rng(SEED)

    fine = seamless_noise((PX, PX), 1.2, rng)      # blade-scale speckle
    mid = seamless_noise((PX, PX), 14.0, rng)      # patchiness, ~0.15 m
    coarse = seamless_noise((PX, PX), 70.0, rng)   # broad wear and dryness

    # Mowing stripes: alternate bands catch the light differently. They are
    # also the scale bar -- STRIPE_M is known, so ground speed can be read off
    # a video frame by counting stripes.
    per_tile = int(round(TILE_M / STRIPE_M))
    y = np.arange(PX)[:, None] / PX * per_tile
    # A softened square wave: tanh of a sine keeps flat bands with a gentle
    # edge, and stays exactly periodic, so it tiles without a seam.
    stripe = np.tanh(3.0 * np.sin(2 * np.pi * y)) * np.ones((1, PX))

    # Dry, slightly yellow field grass rather than a golf green -- a saturated
    # green pushes the detector's colour statistics away from anything in COCO.
    base = np.array([0.17, 0.26, 0.10])
    dry = np.array([0.40, 0.38, 0.18])

    # Keep the broad variation gentle. Strong blotches are what makes a tiled
    # texture read as tiled: the eye finds the repeat by matching the patches.
    t = np.clip(0.42 + 0.13 * coarse + 0.10 * mid, 0.0, 1.0)[..., None]
    rgb = base * (1 - t) + dry * t
    rgb = rgb * (1.0 + 0.15 * fine[..., None] + 0.085 * stripe[..., None])
    img = np.clip(rgb, 0.0, 1.0)

    # sRGB encode: the renderer treats the albedo map as sRGB.
    img = np.where(img <= 0.0031308, img * 12.92,
                   1.055 * np.power(img, 1 / 2.4) - 0.055)
    Image.fromarray((np.clip(img, 0, 1) * 255).astype(np.uint8)).save(
        "materials/textures/grass.jpg", quality=92)

    # No roughness map: grass is uniformly rough, and a noise-filled greyscale
    # map costs a megabyte to say what one constant in the SDF says for free.

    # The mesh: one quad, UVs repeating once per TILE_M.
    h = FIELD_M / 2.0
    rep = FIELD_M / TILE_M
    with open("meshes/ground.obj", "w") as f:
        f.write("# generated by make_ground.py -- do not edit by hand\n")
        f.write("mtllib ground.mtl\no ground\n")
        for x, yv in ((-h, -h), (h, -h), (h, h), (-h, h)):
            f.write(f"v {x:.1f} {yv:.1f} 0.0\n")
        for u, v in ((0, 0), (rep, 0), (rep, rep), (0, rep)):
            f.write(f"vt {u:.1f} {v:.1f}\n")
        f.write("vn 0.0 0.0 1.0\n")
        f.write("usemtl grass\n")
        f.write("f 1/1/1 2/2/1 3/3/1 4/4/1\n")

    with open("meshes/ground.mtl", "w") as f:
        f.write("newmtl grass\nKa 0.4 0.4 0.4\nKd 1.0 1.0 1.0\nKs 0.02 0.02 0.02\n"
                "Ns 1.0\nd 1.0\nillum 2\nmap_Kd ../materials/textures/grass.jpg\n")

    print(f"grass.jpg {PX}x{PX} = {TILE_M} m tile ({1000*TILE_M/PX:.1f} mm/px), "
          f"field {FIELD_M} m, {rep:.0f} tiles across")


if __name__ == "__main__":
    main()
