#!/usr/bin/env python3
"""Generate the course landing pad: a helipad texture and a one-quad mesh.

The aircraft spawns on this pad at the world origin. It is a VISUAL only, with
no collision, on purpose: a pad with a collision shape would change the
spawn height, the contact the land detector sees and, through those, the
take-off the measured numbers in the course were taken with. A visual 3 mm
above the ground changes none of that. The landing legs sink 3 mm into it,
which no camera can see.

What is on it, and why:

  * a white H and ring on a dark surface -- reads as "the place the aircraft
    lives" from any altitude, and gives RTL a visible target;
  * a yellow border, so the pad's edge, and therefore its 2 m size, is a
    scale reference in a screenshot;
  * an arrow along +x (East in ENU), the direction the aircraft's nose points
    at spawn. The frames lecture can point at it: forward is x, and here x
    is East, which is exactly where ENU and NED part ways.

The H's legs run along x, so it reads upright to an aircraft facing the arrow.

Regenerate with:  python3 make_pad.py
"""
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw

SIZE_M = 2.0       # pad edge length; the X500 V2 with props is about 0.95 m across
PX = 1024          # texture resolution -> about 2 mm per pixel
SEED = 11

HERE = Path(__file__).resolve().parent


def m(x):
    """Metres on the pad to pixels."""
    return int(round(x / SIZE_M * PX))


def texture():
    rng = np.random.default_rng(SEED)
    # Dark, slightly mottled surface: a flat colour renders as plastic.
    base = np.full((PX, PX, 3), (52, 55, 58), np.float32)
    base += rng.normal(0, 4.0, (PX, PX, 1))
    img = Image.fromarray(np.clip(base, 0, 255).astype(np.uint8))
    d = ImageDraw.Draw(img)
    white, yellow = (236, 236, 230), (238, 190, 40)
    c = PX / 2

    # Yellow border, 6 cm.
    b = m(0.06)
    d.rectangle([0, 0, PX - 1, PX - 1], outline=yellow, width=b)

    # Ring: outer radius 0.78 m, 8 cm wide.
    ro, w = m(0.78), m(0.08)
    d.ellipse([c - ro, c - ro, c + ro, c + ro], outline=white, width=w)

    # H, 0.9 m long along x, 0.6 m wide, 12 cm strokes. Image rows are -y in
    # the world after the mesh's UV mapping below, and columns are +x.
    hl, hw, s = m(0.90), m(0.60), m(0.12)
    # The two legs run along x; the crossbar runs along y.
    d.rectangle([c - hl / 2, c - hw / 2, c + hl / 2, c - hw / 2 + s], fill=white)
    d.rectangle([c - hl / 2, c + hw / 2 - s, c + hl / 2, c + hw / 2], fill=white)
    d.rectangle([c - s / 2, c - hw / 2, c + s / 2, c + hw / 2], fill=white)

    # Nose arrow along +x, just inside the ring.
    tip, back, half = c + m(0.70), c + m(0.52), m(0.07)
    d.polygon([(tip, c), (back, c - half), (back, c + half)], fill=yellow)
    return img


def mesh():
    """One quad, SIZE_M square, centred on the origin, UVs covering it once.

    v is flipped so that image row 0 is +y: the texture then reads with +x to
    the right and +y up when seen from above, i.e. as drawn.
    """
    h = SIZE_M / 2
    return "\n".join([
        "# course_landing_pad -- generated by make_pad.py",
        "mtllib pad.mtl",
        f"v {-h} {-h} 0", f"v {h} {-h} 0", f"v {h} {h} 0", f"v {-h} {h} 0",
        "vt 0 0", "vt 1 0", "vt 1 1", "vt 0 1",
        "vn 0 0 1",
        "usemtl pad",
        "f 1/1/1 2/2/1 3/3/1 4/4/1",
        "",
    ])


if __name__ == "__main__":
    (HERE / "materials" / "textures").mkdir(parents=True, exist_ok=True)
    (HERE / "meshes").mkdir(exist_ok=True)
    texture().save(HERE / "materials" / "textures" / "pad.png", optimize=True)
    (HERE / "meshes" / "pad.obj").write_text(mesh())
    (HERE / "meshes" / "pad.mtl").write_text(
        "newmtl pad\nKa 1 1 1\nKd 1 1 1\nKs 0 0 0\n"
        "map_Kd ../materials/textures/pad.png\n")
    print("wrote pad.png, pad.obj, pad.mtl")
